name: API Docs
on:
  schedule:
    - cron: "0 10 * * 1-5" # At 10:00 every day-of-week from Monday through Friday.
jobs:
  api-docs:
    name: maas.io/docs/api
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Run Cypress docs tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          config: baseUrl=http://maas.io/
          spec: "cypress/e2e/**/*.{js,jsx,ts,tsx}"
      - name: Create issue on failure
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        with:
          filename: .github/CYPRESS_ISSUE_TEMPLATE.md
          update_existing: true
